
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>


            G_BEGIN_DECLS

/* enumerations from "channel-inputs.h" */


GType spice_inputs_lock_get_type (void);
#define SPICE_TYPE_INPUTS_LOCK (spice_inputs_lock_get_type())

/* enumerations from "spice-channel.h" */


GType spice_channel_event_get_type (void);
#define SPICE_TYPE_CHANNEL_EVENT (spice_channel_event_get_type())

/* enumerations from "spice-session.h" */


GType spice_session_verify_get_type (void);
#define SPICE_TYPE_SESSION_VERIFY (spice_session_verify_get_type())


GType spice_session_migration_get_type (void);
#define SPICE_TYPE_SESSION_MIGRATION (spice_session_migration_get_type())

G_END_DECLS

/* Generated data ends here */

